Devam Ediyoruz... 
Ders 7- Makine Öğrenmesi Algoritmaları ve Numpy....

MAKİNE ÖĞRENMESİ ALGORİTMALARI 
Hepsinden bahsetmeyeceğim çünkü en baştan söylediğim gibi ML bambaşka bir dünya... Veri bilimi Harvard Bussiness Review' da 21. YY ın en seksi mesleği seçildi. :) 

Gelelim algoritmalara: 
K- ENYYAKIN KOMŞU ALGORİTMASI: 

Uygulaması en kolay gözetimli öğrenme algortimalarından biridir. Hem sınıflandırma hem de regresyon problemlerinin çözümünde kullanılıyor olmakla birlikte, endüstride çoğunlukla sınıflandırma problemlerinin çözümünde kullanılmaktadır.
Örnek veri setine katılacak olan yeni verinin, mevcut verilere göre uzaklığı hesaplanıp, k sayıda yakın komşuluğuna bakılır. Uzaklık hesapları için genelde 3 tip uzaklık fonksiyonu kullanılmaktadır:
“Euclidean” Uzaklık
“Manhattan” Uzaklık
“Minkowski” Uzaklığı

KNN; eski, basit ve gürültülü eğitim verilerine karşı dirençli olması sebebiyle en popüler makine öğrenme algoritmalarından biridir. Fakat bunun yanında dezavantajı da mevcuttur. Örneğin, uzaklık hesabı yaparken bütün durumları sakladığından, büyük veriler için kullanıldığında çok sayıda bellek alanına gereksinim duymaktadır.

MONTE CARLO KARAR AĞAÇLARI: ,
Karar problemi, belirlenen amaca ulaşmak için alternatifler arasından en uygun olanının seçilmesini ifade etmektedir. Ancak, bir kararı zorlaştıran, problemin karmaşıklığı, içinde bulunulan durumun belirsizliği, birden fazla amaç, farklı perspektiflerin farklı sonuçlara yol açması, gibi çeşitli nedenler vardır. Karar analizi ise zor kararların verilebilmesi için sistematik bir düşünce tarzı ortaya koymaktadır. 4 adımdan oluşur: Seçim- Genişleme- Karar- Geri Dönüş 

YAPAY SİNİR AĞLARI 

İnsan beynini temel alan bu modelde girdi oluşturulan yapay nöronnlar içinde işlenerek, çıktıya dönüştürülür. Öğrenme sistemi insana benzer. En yaygın kullanılan makine öğrenmesi metodudur. Detaylarına ilerleyen derslerde gireceğim. 

KARINCA KOLONİSİ ALGORİTMASI
Algoritmanın çalışma sürecinde, karıncalar tarafından güncellenen feromon izleriyle iyi bir çözümün bulunması için bilgi oluşturulmakta ve her iterasyonda bu bilgiler güncellenmektedir.

Karınca sayısının arttırılması çözümde iyileşmeye neden olur. Fakat hesaplamaları arttırdığı için karınca sayısının fazla arttırılması işlem zamanlarının uzamasına neden olur.

NUMPY: 
Evet Python severler, geldik kütüphaanelere... Burada en çok kullanacağımız kütüphanelerden biri Numpy. Yani matematiksel işlemleri içeren Python modülü... 
NumPy (Numerical Python) bilimsel hesaplamaları hızlı bir şekilde yapmamızı sağlayan bir matematik kütüphanesidir. 

Gerisi kodlarda... Kolaylıklar... 



#NUMPY' ı anaconda Promptan  pip install numpy komutu ile indirebilirsiniz.. 
#Hadi şimdi kütüphaneyi içe aktaralım yani import edelim 

In [ ]:
import numpy as np #kod listemşizde numpy kullancağımız yerlerde artık np yazmamız yeterli 


#Numpy Array oluşturalım.

In [ ]:
# python list
python_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# numpy array
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) #np.array ile dizi oluşturulur. 
print("Python listesi :")
print(python_list)
print("Numpy dizisi :")
print(numpy_array)


Python listesi :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy dizisi :
[0 1 2 3 4 5 6 7 8 9]


#Dizinin boyutunu bulma: ndarray.ndim

In [ ]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.ndim)

numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)

1
2


#Dizinin satır ve sütun sayısını bulmak: ndarray.shape

In [ ]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.shape)
print(numpy_array1.ndim)
#10 tane elemandan oluşan 1 boyutlu bir dizi(vektör)

print("np.array 2")

numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)
print(numpy_array2.shape)
# 1 satır ve 10 sütundan oluşan 2 boyutlu bir dizi(matris).

(10,)
1
np.array 2
2
(1, 10)


# np.arange() →Python’daki range() fonksiyonuna benzer. Belirtilen başlangıç değerinden başlayıp, her seferinde adım sayısı kadar arttırarak ,bitiş değerine kadar olan sayıları bulunduran bir numpy dizisi dödürür.

In [ ]:
# np.arange(başlangıç,bitiş,adım sayısı)

np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ndarray[:,:] → buradaki “:” kullanımı tüm satır ve sütunları seçmemizi sağlar.

In [ ]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Dizinin herhangi bir satırını seçmek
#1.satır
first_row = numpy_array[0]
#1. ve 2. satır 
first_and_second_rows = numpy_array[0:2]
print(first_row)
print(first_and_second_rows)

print ("----------")

#Dizinin herhangi bir kolonunu seçmek
#1. sütun
first_column = numpy_array[:,0]
#1. ve 2. sütun
first_and_second_column = numpy_array[:,0:2]
print(first_column)
print(first_and_second_column)

print ("----------")

#Dizinin herhangi bir elemanını seçmek
selecting_item = numpy_array[3,1]
print(selecting_item)


[0 1]
[[0 1]
 [2 3]]
----------
[0 2 4 6 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
----------
7


#0 matrisi oluşturmak : np.zeros()

In [ ]:
print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#np.ones(): zeros() fonksiyonuna benzer şeklide verilen büyüklükte 1'lerden oluşan bir matris döndürür.
print(np.ones((5,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#Birim matris oluşturmak : np.eye()

In [ ]:
#4X4 lük birim matris
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#MATEMATİKSEL İŞLEMLER 
#sum(toplam), max ve min değerlerini hesaplamak

In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(numpy_array.max())

9


In [ ]:
print(numpy_array.min())

0


In [ ]:
print(numpy_array.sum())

45


In [ ]:
#Satırların toplamı
print(numpy_array.sum(axis = 1))

[ 1  5  9 13 17]


In [ ]:
#Sütunların toplamı
print(numpy_array.sum(axis = 0))

[20 25]


#mean, median, varyans ve standart sapma hesaplamak


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.mean())

print("------")

print(np.median(numpy_array))

print("------")

print(numpy_array.var())

print("------")

print(numpy_array.std())


4.5
------
4.5
------
8.25
------
2.8722813232690143


#NUMPY' a devam edeceğiz...

In [ ]:
#Matris Transpozu 
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

print ("-----------")

print(numpy_array.T) #".T" ifadesi bizim için Trasnpoz almayı ifade eder.. 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
-----------
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
#Matris Çarpımı 

numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array1 = numpy_array.reshape(5,2)
numpy_array2 = numpy_array.reshape(2,5)
print(np.dot(numpy_array1,numpy_array2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]
